model.qwen2_5_coder_7b_instruct_q4_0.sourceId=hf://Qwen/Qwen2.5-Coder-7B-Instruct-GGUF
model.qwen2_5_coder_7b_instruct_q4_0.markerCoordinate=org.modeljars.huggingface:qwen.qwen2.5-coder-7b-instruct-gguf.q4_0:2.5.0-q4_0.1
model.qwen2_5_coder_7b_instruct_q4_0.modelVersion=2.5.0
model.qwen2_5_coder_7b_instruct_q4_0.variant=q4_0
model.qwen2_5_coder_7b_instruct_q4_0.format=gguf
model.qwen2_5_coder_7b_instruct_q4_0.architecture=qwen2
model.qwen2_5_coder_7b_instruct_q4_0.quantization=Q4_0
model.qwen2_5_coder_7b_instruct_q4_0.path=${user.home}/.jvllm/models/qwen2.5-coder-7b-instruct-q4_0.gguf
model.qwen2_5_coder_7b_instruct_q4_0.sourceUri=https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF
model.qwen2_5_coder_7b_instruct_q4_0.capabilities=text-generation,chat,code-completion
model.qwen2_5_coder_7b_instruct_q4_0.backend.pure-java=true
model.qwen2_5_coder_7b_instruct_q4_0.backend.llama.cpp=true
