model.qwen3_1_7b_q8_0.sourceId=hf://Qwen/Qwen3-1.7B-GGUF
model.qwen3_1_7b_q8_0.markerCoordinate=org.modeljars.huggingface:qwen.qwen3-1.7b-gguf.q8_0:3.0.0-q8_0.1
model.qwen3_1_7b_q8_0.modelVersion=3.0.0
model.qwen3_1_7b_q8_0.variant=q8_0
model.qwen3_1_7b_q8_0.format=gguf
model.qwen3_1_7b_q8_0.architecture=qwen3
model.qwen3_1_7b_q8_0.quantization=Q8_0
model.qwen3_1_7b_q8_0.path=${user.home}/.jvllm/models/Qwen3-1.7B-Q8_0.gguf
model.qwen3_1_7b_q8_0.sourceUri=https://huggingface.co/Qwen/Qwen3-1.7B-GGUF
model.qwen3_1_7b_q8_0.capabilities=text-generation,chat
model.qwen3_1_7b_q8_0.backend.pure-java=true
model.qwen3_1_7b_q8_0.backend.llama.cpp=true
