model.smollm2_360m_instruct_q8_0.sourceId=hf://HuggingFaceTB/SmolLM2-360M-Instruct-GGUF
model.smollm2_360m_instruct_q8_0.markerCoordinate=org.modeljars.huggingface:huggingfacetb.smollm2-360m-instruct-gguf.q8_0:2.0.0-q8_0.1
model.smollm2_360m_instruct_q8_0.modelVersion=2.0.0
model.smollm2_360m_instruct_q8_0.variant=q8_0
model.smollm2_360m_instruct_q8_0.format=gguf
model.smollm2_360m_instruct_q8_0.architecture=llama
model.smollm2_360m_instruct_q8_0.quantization=Q8_0
model.smollm2_360m_instruct_q8_0.path=${user.home}/.jvllm/models/smollm2-360m-instruct-q8_0.gguf
model.smollm2_360m_instruct_q8_0.sourceUri=https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF
model.smollm2_360m_instruct_q8_0.capabilities=text-generation,chat
model.smollm2_360m_instruct_q8_0.backend.pure-java=true
model.smollm2_360m_instruct_q8_0.backend.llama.cpp=true
