package org.modeljars.cli;

import java.net.URI;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Optional;

record ContributionDraft(
    String repository,
    URI sourceUri,
    String revision,
    String name,
    String format,
    Optional<String> architectureHint,
    Optional<String> license,
    List<String> capabilities,
    List<String> domains,
    List<ContributionFile> files) {
  ContributionDraft {
    repository = Objects.requireNonNull(repository, "repository");
    sourceUri = Objects.requireNonNull(sourceUri, "sourceUri");
    revision = Objects.requireNonNull(revision, "revision");
    name = Objects.requireNonNull(name, "name");
    format = Objects.requireNonNull(format, "format").toLowerCase(Locale.ROOT);
    architectureHint = Objects.requireNonNull(architectureHint, "architectureHint");
    license = Objects.requireNonNull(license, "license");
    capabilities = List.copyOf(capabilities);
    domains = List.copyOf(domains);
    files = List.copyOf(files);
    if (!revision.matches("[a-f0-9]{40,64}")) {
      throw new IllegalArgumentException("Resolved revision is not an immutable hexadecimal commit: " + revision);
    }
    if (files.isEmpty()) throw new IllegalArgumentException("A contribution must identify at least one file");
  }

  String title() {
    return "Model candidate: " + name;
  }

  String markdown() {
    StringBuilder body = new StringBuilder();
    body.append("# ModelJars candidate submission\n\n");
    body.append("Generated by `modeljars contribute`. Candidate intake does not claim Models compatibility or qualification.\n\n");
    body.append("<!-- modeljars-candidate-v1 -->\n\n");
    body.append("## Upstream identity\n\n");
    row(body, "Repository", sourceUri.toString());
    row(body, "Revision", code(revision));
    row(body, "Format", code(format));
    row(body, "Name", name);
    row(body, "License", license.orElse("Needs maintainer review"));
    row(body, "Architecture hint", architectureHint.orElse("Not reported upstream"));
    row(body, "Capabilities", capabilities.isEmpty() ? "Not specified" : String.join(", ", capabilities));
    row(body, "Domains", domains.isEmpty() ? "general" : String.join(", ", domains));
    body.append("\n## Immutable files\n\n");
    body.append("| Path | Role | Bytes | SHA-256 |\n| --- | --- | ---: | --- |\n");
    for (ContributionFile file : files) {
      body.append("| ")
          .append(markdownText(file.path()))
          .append(" | ")
          .append(markdownText(file.role()))
          .append(" | ")
          .append(file.sizeBytes())
          .append(" | `")
          .append(file.sha256())
          .append("` |\n");
    }
    body.append("\n## Maintainer qualification\n\n");
    body.append("- [ ] Confirm license and intended capabilities.\n");
    body.append("- [ ] Add or verify exact-artifact parser, tokenizer, and execution tests in Integrallis Models.\n");
    body.append("- [ ] Run the applicable controlled generation, embedding, or other capability qualification.\n");
    body.append("- [ ] Add an immutable marker coordinate and reviewed catalog metadata.\n");
    return body.toString();
  }

  private static void row(StringBuilder body, String label, String value) {
    body.append("- **").append(label).append(":** ").append(markdownText(value)).append('\n');
  }

  private static String code(String value) {
    return "`" + value + "`";
  }

  private static String markdownText(String value) {
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ");
  }
}
